M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Wed 10 Apr 2024 19:00:27 BST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-10T19:00:27+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X0.364Y-0.7551
X0.7805Y-0.7539
T2
X0.2264Y-1.0335
X0.9154Y-0.1083
M30
